version: '3.8'

services:
  JAQp-db:
    image: 'postgres:latest'
    container_name: JAQp-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=JAQp
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
#     - ./schema:/docker-entrypoint-initdb.d   
  JAQp-minio:
    image: minio/minio
    container_name: JAQp-minio
    ports:
          - "9000:9000"
          - "9001:9001"
    volumes:
          - minio-data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio 
    command: server --console-address ":9001" /data
  JAQp-Garnet:
    image: 'ghcr.io/microsoft/garnet'
    restart: always
    container_name: JAQp-Garnet
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # To avoid docker NAT, consider `host` mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - cache:/data
volumes:
  cache:
  pg-data:
  minio-data:
  
